module.exports = async ({github, context, head, base, autoMerge = true, title = 'Automated Pull Request'}) => {
    const { repo, owner } = context.repo;
    const result = await github.rest.pulls.create({
      title,
      owner,
      repo,
      head,
      base,
      body: 'This PR is auto-generated by Github Action'
    });
  
    await github.rest.issues.addLabels({
      owner,
      repo,
      issue_number: result.data.number,
      labels: [base, 'automated pr']
    });
  
    if(autoMerge){
      const pull_number = result.data.number
      const merge_method = 'merge';
      const mergeResult = await github.rest.pulls.merge({
        owner,
        repo,
        pull_number,
        merge_method
      });
  
      if(mergeResult.status != 200) {
        const state = 'closed';
        await github.rest.pulls.update({
          owner,
          repo,
          pull_number,
          state
        });
      }
      return mergeResult;
    }
  }