name: Check if test branch2 contains last commit from branch1

on:
  workflow_call:
    inputs:
      branch1:
        required: true
        type: string
      branch2:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if test branch2 contains last commit from branch1
        run: |
          last_commit=$(git log --format="%H" -n 1 origin/${{ inputs.branch1 }})
          echo $last_commit
          if git branch -a --contains $last_commit | grep -q "remotes/origin/${{ inputs.branch2 }}$"; then
            echo "Test branch contains the last commit from development branch."
            exit 1 # Exit with an error code
          else
            echo "Test branch does not contain the last commit from development branch."
            exit 0 # Exit successfully
          fi
