name: Prod - Release minor

on:
  workflow_dispatch:

jobs:
  minor-bump-commit:
    name: Bump minor version and push commit to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request, Auto-approve & Merge
        id: pr
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/createPullRequestAutoApproveAndMerge.js')
            return await script({github, context, head: 'qa', base: 'main', title: 'Automatic merge development into test'})

      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Create new branch and bump minor version
        id: minorBumpCreateBranch
        run: |
          git config --global user.email "github.actions@github.com"
          git config --global user.name "Github actions"

          branch="version-minor-${GITHUB_RUN_ID}"
          git switch --create "${branch}"
          npm version minor
          version=$(node -p "require('./package.json').version")
          git push --set-upstream origin "${branch}"
          git rev-parse HEAD
          commitHash=$?
          echo "branch=$branch" >> $GITHUB_OUTPUT 
          echo "commitHash=$commitHash" >> $GITHUB_OUTPUT

      - name: Create Pull Request for bumping minor version into main
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/createPullRequestAutoApproveAndMerge.js')
            console.log('commitHash: ', '${{ steps.minorBumpCreateBranch.outputs.commitHash }}')
            return await script({github, context, head: '', base: 'main', autoMerge: false, title: 'Automatic bump minor version'})

      - uses: actions/checkout@v4
        with:
          ref: development
      - name: Create new branch and cherry pick commit
        id: cherryPickCreateBranch
        run: |
          git config --global user.email "github.actions@github.com"
          git config --global user.name "Github actions"
          branch="version-minor-cherry-${GITHUB_RUN_ID}"
          git switch --create "${branch}"
          git cherry-pick ${{ steps.minorBumpCreateBranch.outputs.commitHash }}
          git push --set-upstream origin "${branch}"
          echo "branch=$branch" >> $GITHUB_OUTPUT

      - name: Create Pull Request for cherry pick minor version into development
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/createPullRequestAutoApproveAndMerge.js')
            return await script({github, context, head: '${{ steps.cherryPickCreateBranch.outputs.branch }}', base: 'development', autoMerge: false, title: 'Automatic cherry pick minor version'})
